import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/sass/admin/app.scss',
                'resources/js/app.js',
                'resources/js/core/bootstrap.bundle.min.js',
                'resources/js/material-kit-pro.js',
                'resources/js/plugins/anime.min.js',
                'resources/js/plugins/countup.min.js',
                'resources/js/plugins/glidejs.min.js',
                'resources/js/plugins/nouislider.min.js',
                'resources/js/plugins/photoswipe-ui-default.min.js',
                'resources/js/plugins/prism.min.js',
                'resources/js/plugins/smooth-scroll.min.js',
                'resources/js/plugins/chartjs.min.js',
                'resources/js/plugins/flatpickr.min.js',
                'resources/js/plugins/highlight.min.js',
                'resources/js/plugins/parallax.min.js',
                'resources/js/plugins/photoswipe.min.js',
                'resources/js/plugins/rellax.min.js',
                'resources/js/plugins/tilt.min.js',
                'resources/js/plugins/choices.min.js',
                'resources/js/plugins/glide.min.js',
                'resources/js/plugins/moment.min.js',
                'resources/js/plugins/perfect-scrollbar.min.js',
                'resources/js/plugins/round-slider.min.js',
                'resources/js/plugins/typedjs.js',
                'resources/js/admin/app.js',
                'resources/js/admin/material-dashboard.js',
                'resources/js/admin/plugins/amcharts/animated.js',
                'resources/js/admin/plugins/amcharts/core.js',
                'resources/js/admin/plugins/amcharts/maps.js',
                'resources/js/admin/plugins/amcharts/worldLow.js',
                'resources/js/admin/plugins/dragula/dragula.js',
                'resources/js/admin/plugins/jkanban/jkanban.js',
                'resources/js/admin/plugins/countup.min.js',
                'resources/js/admin/plugins/dropzone.min.js',
                'resources/js/admin/plugins/multistep-form.js',
                'resources/js/admin/plugins/parallax.min.js',
                'resources/js/admin/plugins/photoswipe.min.js',
                'resources/js/admin/plugins/smooth-scrollbar.min.js',
                'resources/js/admin/plugins/tilt.min.js',
                'resources/js/admin/plugins/chartjs.min.js',
                'resources/js/admin/plugins/datatables.js',
                'resources/js/admin/plugins/flatpickr.min.js',
                'resources/js/admin/plugins/leaflet.js',
                'resources/js/admin/plugins/nouislider.min.js',
                'resources/js/admin/plugins/perfect-scrollbar.min.js',
                'resources/js/admin/plugins/quill.min.js',
                'resources/js/admin/plugins/sweetalert.min.js',
                'resources/js/admin/plugins/world.js',
                'resources/js/admin/plugins/choices.min.js',
                'resources/js/admin/plugins/fullcalendar.min.js',
                'resources/js/admin/plugins/moment.min.js',
                'resources/js/admin/plugins/orbit-controls.js',
                'resources/js/admin/plugins/photoswipe-ui-default.min.js',
                'resources/js/admin/plugins/round-slider.min.js',
                'resources/js/admin/plugins/threejs.js',
                'resources/js/admin/core/bootstrap.bundle.min.js',
            ],
            refresh: true,
        }),
    ],
});
